"""Duty-formation and depot-assignment post-processing.

After routes are generated by the VRPTW solver, this module:
    1. Assigns each route to a depot (start/end must match).
    2. Groups routes into driver duties.
    3. Validates duty spread, driving hours, and refueling constraints.
"""

from __future__ import annotations

import logging
from typing import Any

import pandas as pd

from services.matrix_builder import _haversine_km
from utils.validators import (
    MAX_DUTY_SPREAD,
    MAX_DRIVING_PER_SHIFT,
    REFUELING_TIME,
    check_depot_consistency,
    check_driving_hours,
    check_duty_spread,
    check_refueling,
)

logger = logging.getLogger(__name__)


def assign_routes_to_depots(
    routes: list[dict[str, Any]],
    depot_df: pd.DataFrame,
) -> list[dict[str, Any]]:
    """Assign each route to the nearest depot based on the first stop lat/lng.

    Modifies routes in place, adding ``depot_start`` and ``depot_end`` (equal).
    """
    depots = depot_df[["depot_code", "lat", "lon"]].dropna().to_dict("records")
    for route in routes:
        stops = route.get("stop_sequence", [])
        if not stops:
            continue
        first = stops[0]
        best_code = depots[0]["depot_code"] if depots else "UNKNOWN"
        best_dist = float("inf")
        for d in depots:
            dist = _haversine_km(first["lat"], first["lng"], d["lat"], d["lon"])
            if dist < best_dist:
                best_dist = dist
                best_code = d["depot_code"]
        route["depot_start"] = best_code
        route["depot_end"] = best_code  # same depot for start and sign-off
        route["depot"] = best_code
    return routes


def form_duties(
    routes: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Group routes into duties and compute duty-level metrics.

    Simple heuristic: each route is its own duty for now.
    TODO: merge compatible routes into multi-trip duties.

    Returns list of duty dicts with:
        duty_id, routes, total_driving_min, duty_spread_min,
        includes_refueling, violations
    """
    duties: list[dict[str, Any]] = []
    for i, route in enumerate(routes):
        driving = route.get("estimated_duration", 0)
        spread = driving + REFUELING_TIME
        duty = {
            "duty_id": f"D-{i+1:03d}",
            "routes": [route["route_id"]],
            "depot": route.get("depot", ""),
            "total_driving_min": driving,
            "duty_spread_min": spread,
            "includes_refueling": True,
            "violations": [],
        }

        # Validate
        duty["violations"].append(
            check_depot_consistency(duty["duty_id"], route.get("depot_start", ""), route.get("depot_end", ""))
        )
        duty["violations"].append(
            check_duty_spread(duty["duty_id"], spread)
        )
        duty["violations"].append(
            check_driving_hours(duty["duty_id"], driving)
        )
        duty["violations"].append(
            check_refueling(duty["duty_id"], True)
        )
        duties.append(duty)
    return duties


def duties_to_dataframe(duties: list[dict[str, Any]]) -> pd.DataFrame:
    rows = []
    for d in duties:
        violation_count = sum(1 for v in d["violations"] if v["status"] != "pass")
        rows.append({
            "duty_id": d["duty_id"],
            "routes": ", ".join(d["routes"]),
            "depot": d["depot"],
            "driving_min": d["total_driving_min"],
            "spread_min": d["duty_spread_min"],
            "refueling": "是" if d["includes_refueling"] else "否",
            "violations": violation_count,
        })
    return pd.DataFrame(rows)
